# config.py

# Constants used by simulation
HOME_POSITION = (0, 0)
FLY_HEIGHT = 1.0
SECTION_SWEEP_STEPS = 4
SEARCH_OFFSET = (6, 4)
WAYPOINT_TOLERANCE = 0.40
HOVER_TIME = 0.05
MAX_SPEED = 6.0
BROADCAST_PERIOD = 5.0  # seconds
RETURN_TIMEOUT = 10.0

# Simulation
CTRL_FREQ = 60
GRID_SIZE = 4
SECTION_SIZE = 1.5

# Physics/Logic
CRASH_HEIGHT_THRESHOLD = 0.1
CRASH_TIMEOUT = 6.0
BATTERY_CHANGE_DURATION = 60.0
MAX_FRAME_TIME = 0.25

# Search/Detection
SUBJECT_DETECTION_DIST = 0.4
VERIFICATION_DIST = 0.25
VOTING_RADIUS = 0.5
VOTING_ANGLES = [0, 120, 240]

# Market
STARTING_POINTS = 3.0
SECTION_BASE_VALUE = 2.0
FORCE_BUY_COST = 2.0
DYNAMIC_PRICE_FACTOR = 10.0

# Flight Control
# Options: "standard", "aggressive", "path_follow", "smooth_follow"
FLIGHT_MODE = "aggressive"

# Collision Avoidance
AVOID_DRONE_RADIUS = 0.5
AVOID_DRONE_MAX_PUSH = 0.4
AVOID_DRONE_GAIN_NAV = 0.2
AVOID_DRONE_GAIN_VERIFY = 0.3 # Higher gain during verification/hovering
AVOID_BORDER_GAIN = 0.1
AVOID_BORDER_MAX_PUSH = 0.0 # Often 0 to just be a soft force or unused? Actually code used 0.
AVOID_BORDER_MARGIN_NAV = 0.1
AVOID_BORDER_MARGIN_VERIFY = 0.3
